on:
  push:
    branches:    
      - main
    paths:
      - 'VERSION'
  pull_request:
    branches:
      - main
    paths:
      - 'VERSION'

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: pipe-cd/actions-gh-release@95c51c646e75db5c6b7d447e3087bcee58677341
        with:
          version_file: 'VERSION'
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
